name: salve
version: 0.0.7

category: Distribution
description:
  Salve provides semantic version (SemVer) numbers and constraints (ranges).
extra-source-files:
  - CHANGELOG.markdown
  - README.markdown
github: tfausak/salve
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Semantic version numbers and constraints.

dependencies: base >=4.7.0 && <4.11
ghc-options: -Wall

library:
  source-dirs: library

tests:
  doctest:
    dependencies:
      - doctest >=0.9.11 && <0.14
      - microlens >=0.2.0 && <0.5
    main: doctest.hs
    source-dirs: tests

benchmarks:
  benchmark:
    dependencies:
      - criterion >=1.1.0 && <1.3
      - deepseq >=1.4.1 && <1.5
      - salve
      - semver >=0.3.3 && <0.4
      - semver-range >=0.2.2 && <0.3
    main: benchmark.hs
    source-dirs: benchmarks
