name: salve
version: 1.0.2

category: Distribution
description:
  Salve provides semantic version (SemVer) numbers and constraints (ranges).
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/salve
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Semantic version numbers and constraints.

dependencies:
  base: '>= 4.9.0 && < 4.12'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

tests:
  doctest:
    dependencies:
      doctest: '>= 0.11.0 && < 0.16'
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: tests
