name: salve
version: 0.0.8

category: Distribution
description:
  Salve provides semantic version (SemVer) numbers and constraints (ranges).
extra-source-files:
  - CHANGELOG.markdown
  - README.markdown
github: tfausak/salve
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Semantic version numbers and constraints.

dependencies:
  - base >=4.7.0 && <4.11
ghc-options:
  - -Wall

library:
  source-dirs: library

tests:
  doctest:
    dependencies:
      - doctest >=0.9.11 && <0.14
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: tests
